### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by MatthewSteeples** [unitycontainer/registration-by-convention#3]
Are there any plans to include this alongside the official releases on NuGet?

**Comment by MatthewSteeples** [comment]
Sorry, just found the discussion from here: https://github.com/unitycontainer/container/issues/27

Guessing it's still a work in progress

**Comment by ENikS** [comment]
You are welcome to send a pull request with a fix.
I don’t think i’ll be able to get to it this week.

**Comment by MatthewSteeples** [comment]
@ENikS Will look into it. Only reason I hadn't was that I didn't want to "own" the NuGet package if someone else was already working on it

**Comment by ENikS** [comment]
No need for that. If you send the pr, I’ll release the package as part of the library.
