### ISSUE TITLE
Please add support for MonoAndroid 8.0 / Xamarin

### ISSUE THREAD

**Issue by randalvance** [unitycontainer/registration-by-convention#4]
I cannot install this into my Xamarin project as I am receiving the following error:

> Could not install package 'Unity.RegistrationByConvention 2.1.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v8.0', but the package does not contain any assembly references or content files that are compatible with that framework. 

Thank you

**Comment by ENikS** [comment]
This is due to [this issue](https://github.com/unitycontainer/registration-by-convention/issues/2). Someone with platform knowledge should help out and fix it.

Duplicate #2
